default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build release APK for F-Droid"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  # Optional: keep beta and deploy if you want, but comment out uploads
  lane :beta do
    gradle(task: "clean assembleRelease")
    # crashlytics
  end

  lane :deploy do
    gradle(task: "clean assembleRelease")
    # upload_to_play_store
  end
end
